sources:
  npm: true

allowed:
  - apache-2.0
  - 0bsd
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - blueoak-1.0.0

reviewed:
  npm:
    - "@actions/http-client" # MIT (license text present), but detected as "other"
    - "argparse" # Python Software Foundation License (PSF), but detected as "other"
    - "balanced-match"
    - "brace-expansion"
    - "readable-stream" # MIT (two MIT blocks in one file), but detected as "other"
    - "retry" # MIT (no title line), but detected as "other"
    - "string_decoder" # MIT (two MIT blocks in one file), but detected as "other"
